In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ruta = r"C:\Users\Sam\Desktop\Proyecto Crimen\BASE_DATOS_CRIMINALIDAD_CON_INDICES_2023_2025.xlsx"

df = pd.read_excel(
    ruta,
    sheet_name="FACT_Criminalidad"
)

df.head()

,año,trimestre,ID crimen,tipo de crimen,Ccodigo postal,municipio,conteo,Conteo Día,Conteo Noche,Puntuación crimen,Grupo,Conteo ponderado,Día ponderado,Noche ponderado
0,2025,Q1,1.0,Homicidios dolosos y asesinatos consumados,28005.0,Alcalá de Henares,1,0,1,10,Violencia extrema,10,0,10
1,2025,Q1,1.0,Homicidios dolosos y asesinatos consumados,28006.0,Alcobendas,0,0,0,10,Violencia extrema,0,0,0
2,2025,Q1,1.0,Homicidios dolosos y asesinatos consumados,28007.0,Alcorcón,0,0,0,10,Violencia extrema,0,0,0
3,2025,Q1,1.0,Homicidios dolosos y asesinatos consumados,28009.0,Algete,0,0,0,10,Violencia extrema,0,0,0
4,2025,Q1,1.0,Homicidios dolosos y asesinatos consumados,28013.0,Aranjuez,0,0,0,10,Violencia extrema,0,0,0

In [19]:
print("Dimensiones del dataset:", df.shape)

print("\nColumnas:")
print(df.columns.tolist())

print("\nInformación general:")
df.info()

Dimensiones del dataset: (6848, 14)

Columnas:
['año', 'trimestre', 'ID crimen', 'tipo de crimen', 'Ccodigo postal', 'municipio', 'conteo', 'Conteo Día', 'Conteo Noche', 'Puntuación crimen', 'Grupo', 'Conteo ponderado', 'Día ponderado', 'Noche ponderado']

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6848 entries, 0 to 6847
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   año                6848 non-null   int64
 1   trimestre          6848 non-null   object
 2   ID crimen          6848 non-null   float64
 3   tipo de crimen     6848 non-null   object
 4   Ccodigo postal     6784 non-null   float64
 5   municipio          6848 non-null   object
 6   conteo             6848 non-null   int64
 7   Conteo Día         6848 non-null   int64
 8   Conteo Noche       6848 non-null   int64
 9   Puntuación crimen  6848 non-null   int64
 10  Grupo              6848 non-null   object
 11  Conteo ponderado   6848 non-null   int64
 12  Día ponderado      6848 non-null   int64
 13  Noche ponderado    6848 non-null   int64
dtypes: float64(2), int64(8), object(4)
memory usage: 749.1+ KB

In [20]:
df.describe(include="all")

,año,trimestre,ID crimen,tipo de crimen,Ccodigo postal,municipio,conteo,Conteo Día,Conteo Noche,Puntuación crimen,Grupo,Conteo ponderado,Día ponderado,Noche ponderado
count,6848.000000,6848,6848.000000,6848,6784.000000,6848,6848.000000,6848.000000,6848.000000,6848.000000,6848,6848.000000,6848.000000,6848.000000
unique,NaN,4,NaN,16,NaN,37,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
top,NaN,Q1,NaN,Homicidios dolosos y asesinatos consumados,NaN,Alcalá de Henares,NaN,NaN,NaN,NaN,Delitos contra el patrimonio,NaN,NaN,NaN
freq,NaN,1712,NaN,428,NaN,192,NaN,NaN,NaN,NaN,1712,NaN,NaN,NaN
mean,2024.028037,NaN,6.775000,NaN,28103.169811,NaN,167.445386,112.406834,55.045415,6.062062,NaN,486.185310,292.080315,194.146466
std,0.814163,NaN,3.428533,NaN,145.655073,NaN,1359.449831,935.023957,460.050811,2.794208,NaN,3595.304412,2313.140921,1376.573976
min,2023.000000,NaN,1.000000,NaN,28005.000000,NaN,-3.000000,-3.000000,0.000000,2.000000,NaN,-6.000000,-6.000000,0.000000
25%,2023.000000,NaN,4.750000,NaN,28040.000000,NaN,1.000000,0.000000,1.000000,3.750000,NaN,9.000000,0.000000,4.000000
50%,2024.000000,NaN,6.500000,NaN,28080.000000,NaN,9.000000,3.000000,4.000000,6.000000,NaN,48.000000,16.000000,24.000000
75%,2025.000000,NaN,9.250000,NaN,28127.000000,NaN,43.000000,20.000000,15.000000,8.000000,NaN,165.000000,76.000000,77.000000
max,2025.000000,NaN,13.000000,NaN,28903.000000,NaN,24708.000000,17941.000000,9883.000000,10.000000,NaN,74124.000000,44475.000000,29649.000000

In [21]:
print("Años:", sorted(df["año"].unique()))
print("Trimestres:", sorted(df["trimestre"].unique()))
print("Municipios:", df["municipio"].nunique())
print("Tipos de crimen:", df["tipo de crimen"].nunique())

Años: [np.int64(2023), np.int64(2024), np.int64(2025)]
Trimestres: ['Q1', 'Q2', 'Q3', 'Q4']
Municipios: 37
Tipos de crimen: 16

In [22]:
print("Grupos:", df["Grupo"].nunique())
print("Nulos por columna:")
print(df.isnull().sum().sort_values(ascending=False))

Grupos: 8
Nulos por columna:
Ccodigo postal       64
año                   0
trimestre             0
ID crimen             0
tipo de crimen        0
municipio             0
conteo                0
Conteo Día            0
Conteo Noche          0
Puntuación crimen     0
Grupo                 0
Conteo ponderado      0
Día ponderado         0
Noche ponderado       0
dtype: int64

In [23]:
# Comprobar duplicados en cada serie temporal

duplicados = df.duplicated(
    subset=["municipio", "tipo de crimen", "año", "trimestre"],
    keep=False
)

print("Número de filas duplicadas:", duplicados.sum())

df[duplicados].sort_values(
    ["municipio", "tipo de crimen", "año", "trimestre"]
).head(20)

Número de filas duplicadas: 0

Empty DataFrame
Columns: [año, trimestre, ID crimen, tipo de crimen, Ccodigo postal, municipio, conteo, Conteo Día, Conteo Noche, Puntuación crimen, Grupo, Conteo ponderado, Día ponderado, Noche ponderado]
Index: []

In [24]:
# Crear un orden temporal continuo
orden_trimestre = {
    "Q1": 1,
    "Q2": 2,
    "Q3": 3,
    "Q4": 4
}

df["num_trimestre"] = df["trimestre"].map(orden_trimestre)

# Crear índice temporal consecutivo:
# 2023 Q1 = 0, 2023 Q2 = 1 ... 2025 Q4 = 11
df["periodo_num"] = (
    (df["año"] - 2023) * 4
    + df["num_trimestre"] - 1
)

# Comprobar número de registros por año
print("Registros por año:")
print(df.groupby("año").size())

print("\nMunicipios por año:")
print(df.groupby("año")["municipio"].nunique())

print("\nRango temporal:")
print(df["periodo_num"].min(), "-", df["periodo_num"].max())

Registros por año:
año
2023    2176
2024    2304
2025    2368
dtype: int64

Municipios por año:
año
2023    34
2024    36
2025    37
Name: municipio, dtype: int64

Rango temporal:
0 - 11

In [25]:
municipios_2023 = set(df[df["año"] == 2023]["municipio"].unique())
municipios_2024 = set(df[df["año"] == 2024]["municipio"].unique())
municipios_2025 = set(df[df["año"] == 2025]["municipio"].unique())

print("Nuevos en 2024:")
print(sorted(municipios_2024 - municipios_2023))

print("\nNuevos en 2025:")
print(sorted(municipios_2025 - municipios_2024))

print("\nPresentes en 2023 pero ausentes en 2024:")
print(sorted(municipios_2023 - municipios_2024))

print("\nPresentes en 2024 pero ausentes en 2025:")
print(sorted(municipios_2024 - municipios_2025))

Nuevos en 2024:
['San Martín de la Vega', 'Villanueva de la Cañada']

Nuevos en 2025:
['Humanes de Madrid']

Presentes en 2023 pero ausentes en 2024:
[]

Presentes en 2024 pero ausentes en 2025:
[]

In [26]:
# ==========================================
# CREACIÓN DEL DATASET TEMPORAL PARA EL MODELO
# ==========================================

# Creamos una copia para no modificar el dataframe original
df_modelo = df.copy()

# Ordenamos cronológicamente cada serie
df_modelo = df_modelo.sort_values(
    by=["municipio", "tipo de crimen", "periodo_num"]
).reset_index(drop=True)

# Definimos cada serie temporal
grupo_serie = df_modelo.groupby(
    ["municipio", "tipo de crimen"]
)

# Creamos los lags sobre la variable que queremos predecir: conteo
df_modelo["lag_1"] = grupo_serie["conteo"].shift(1)
df_modelo["lag_2"] = grupo_serie["conteo"].shift(2)
df_modelo["lag_3"] = grupo_serie["conteo"].shift(3)
df_modelo["lag_4"] = grupo_serie["conteo"].shift(4)

# Visualizamos el resultado
df_modelo[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo",
        "lag_1",
        "lag_2",
        "lag_3",
        "lag_4"
    ]
].head(15)

,municipio,tipo de crimen,año,trimestre,conteo,lag_1,lag_2,lag_3,lag_4
0,Alcalá de Henares,Agresión sexual con penetración,2023,Q1,1,NaN,NaN,NaN,NaN
1,Alcalá de Henares,Agresión sexual con penetración,2023,Q2,2,1.0,NaN,NaN,NaN
2,Alcalá de Henares,Agresión sexual con penetración,2023,Q3,4,2.0,1.0,NaN,NaN
3,Alcalá de Henares,Agresión sexual con penetración,2023,Q4,1,4.0,2.0,1.0,NaN
4,Alcalá de Henares,Agresión sexual con penetración,2024,Q1,7,1.0,4.0,2.0,1.0
5,Alcalá de Henares,Agresión sexual con penetración,2024,Q2,2,7.0,1.0,4.0,2.0
6,Alcalá de Henares,Agresión sexual con penetración,2024,Q3,3,2.0,7.0,1.0,4.0
7,Alcalá de Henares,Agresión sexual con penetración,2024,Q4,1,3.0,2.0,7.0,1.0
8,Alcalá de Henares,Agresión sexual con penetración,2025,Q1,5,1.0,3.0,2.0,7.0
9,Alcalá de Henares,Agresión sexual con penetración,2025,Q2,1,5.0,1.0,3.0,2.0
10,Alcalá de Henares,Agresión sexual con penetración,2025,Q3,4,1.0,5.0,1.0,3.0
11,Alcalá de Henares,Agresión sexual con penetración,2025,Q4,5,4.0,1.0,5.0,1.0
12,Alcalá de Henares,Delitos contra la libertad sexual,2023,Q1,13,NaN,NaN,NaN,NaN
13,Alcalá de Henares,Delitos contra la libertad sexual,2023,Q2,12,13.0,NaN,NaN,NaN
14,Alcalá de Henares,Delitos contra la libertad sexual,2023,Q3,16,12.0,13.0,NaN,NaN

In [27]:
# ==========================================
# FEATURE ENGINEERING TEMPORAL
# ==========================================

# Media de los 4 trimestres anteriores
df_modelo["media_movil_4"] = (
    df_modelo[["lag_1", "lag_2", "lag_3", "lag_4"]]
    .mean(axis=1)
)

# Tendencia reciente:
# cambio entre el último trimestre conocido y el anterior
df_modelo["tendencia_reciente"] = (
    df_modelo["lag_1"] - df_modelo["lag_2"]
)

# Variación respecto al mismo trimestre del año anterior
# Comparamos el trimestre anterior con el dato de hace 4 trimestres
df_modelo["variacion_interanual"] = (
    df_modelo["lag_1"] - df_modelo["lag_4"]
)

# Visualizamos
df_modelo[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo",
        "lag_1",
        "lag_2",
        "lag_3",
        "lag_4",
        "media_movil_4",
        "tendencia_reciente",
        "variacion_interanual"
    ]
].head(12)

,municipio,tipo de crimen,año,trimestre,conteo,lag_1,lag_2,lag_3,lag_4,media_movil_4,tendencia_reciente,variacion_interanual
0,Alcalá de Henares,Agresión sexual con penetración,2023,Q1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alcalá de Henares,Agresión sexual con penetración,2023,Q2,2,1.0,NaN,NaN,NaN,1.000000,NaN,NaN
2,Alcalá de Henares,Agresión sexual con penetración,2023,Q3,4,2.0,1.0,NaN,NaN,1.500000,1.0,NaN
3,Alcalá de Henares,Agresión sexual con penetración,2023,Q4,1,4.0,2.0,1.0,NaN,2.333333,2.0,NaN
4,Alcalá de Henares,Agresión sexual con penetración,2024,Q1,7,1.0,4.0,2.0,1.0,2.000000,-3.0,0.0
5,Alcalá de Henares,Agresión sexual con penetración,2024,Q2,2,7.0,1.0,4.0,2.0,3.500000,6.0,5.0
6,Alcalá de Henares,Agresión sexual con penetración,2024,Q3,3,2.0,7.0,1.0,4.0,3.500000,-5.0,-2.0
7,Alcalá de Henares,Agresión sexual con penetración,2024,Q4,1,3.0,2.0,7.0,1.0,3.250000,1.0,2.0
8,Alcalá de Henares,Agresión sexual con penetración,2025,Q1,5,1.0,3.0,2.0,7.0,3.250000,-2.0,-6.0
9,Alcalá de Henares,Agresión sexual con penetración,2025,Q2,1,5.0,1.0,3.0,2.0,2.750000,4.0,3.0
10,Alcalá de Henares,Agresión sexual con penetración,2025,Q3,4,1.0,5.0,1.0,3.0,2.500000,-4.0,-2.0
11,Alcalá de Henares,Agresión sexual con penetración,2025,Q4,5,4.0,1.0,5.0,1.0,2.750000,3.0,3.0

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ==========================================
# BASELINE ESTACIONAL - AÑO 2025
# ==========================================

# Seleccionamos 2025 y solo filas con lag_4 disponible
df_baseline = df_modelo[
    (df_modelo["año"] == 2025) &
    (df_modelo["lag_4"].notna())
].copy()

# Valor real
y_real = df_baseline["conteo"]

# Predicción baseline:
# mismo trimestre del año anterior
y_pred_baseline = df_baseline["lag_4"]

# Métricas
mae_baseline = mean_absolute_error(y_real, y_pred_baseline)
rmse_baseline = np.sqrt(
    mean_squared_error(y_real, y_pred_baseline)
)
r2_baseline = r2_score(y_real, y_pred_baseline)

print("RESULTADOS BASELINE ESTACIONAL 2025")
print("=" * 40)
print(f"MAE:  {mae_baseline:.2f}")
print(f"RMSE: {rmse_baseline:.2f}")
print(f"R²:   {r2_baseline:.4f}")
print()
print("Número de observaciones:", len(df_baseline))

RESULTADOS BASELINE ESTACIONAL 2025
========================================
MAE:  18.43
RMSE: 112.51
R²:   0.9926

Número de observaciones: 2304

In [29]:
# ==========================================
# BASELINE EXCLUYENDO MADRID CAPITAL
# ==========================================

df_sin_madrid = df_baseline[
    df_baseline["municipio"] != "Madrid"
].copy()

y_real_sin_madrid = df_sin_madrid["conteo"]
y_pred_sin_madrid = df_sin_madrid["lag_4"]

mae_sin_madrid = mean_absolute_error(
    y_real_sin_madrid,
    y_pred_sin_madrid
)

rmse_sin_madrid = np.sqrt(
    mean_squared_error(
        y_real_sin_madrid,
        y_pred_sin_madrid
    )
)

r2_sin_madrid = r2_score(
    y_real_sin_madrid,
    y_pred_sin_madrid
)

print("BASELINE 2025 - SIN MADRID CAPITAL")
print("=" * 40)
print(f"MAE:  {mae_sin_madrid:.2f}")
print(f"RMSE: {rmse_sin_madrid:.2f}")
print(f"R²:   {r2_sin_madrid:.4f}")

BASELINE 2025 - SIN MADRID CAPITAL
========================================
MAE:  10.69
RMSE: 25.63
R²:   0.9688

In [30]:
# ==========================================
# WAPE DEL BASELINE
# ==========================================

wape_baseline = (
    np.abs(y_real - y_pred_baseline).sum()
    / np.abs(y_real).sum()
) * 100

wape_sin_madrid = (
    np.abs(y_real_sin_madrid - y_pred_sin_madrid).sum()
    / np.abs(y_real_sin_madrid).sum()
) * 100

print(f"WAPE global:     {wape_baseline:.2f}%")
print(f"WAPE sin Madrid: {wape_sin_madrid:.2f}%")

WAPE global:     11.39%
WAPE sin Madrid: 17.49%

In [31]:
# ==========================================
# MAYORES ERRORES DEL BASELINE
# ==========================================

df_baseline["prediccion_baseline"] = df_baseline["lag_4"]

df_baseline["error_absoluto"] = np.abs(
    df_baseline["conteo"]
    - df_baseline["prediccion_baseline"]
)

df_baseline[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo",
        "prediccion_baseline",
        "error_absoluto"
    ]
].sort_values(
    "error_absoluto",
    ascending=False
).head(20)

,municipio,tipo de crimen,año,trimestre,conteo,prediccion_baseline,error_absoluto
3408,Madrid,Hurtos,2025,Q1,19067,22220.0,3153.0
3375,Madrid,Estafas informáticas,2025,Q4,5721,8262.0,2541.0
3409,Madrid,Hurtos,2025,Q2,18316,20543.0,2227.0
3411,Madrid,Hurtos,2025,Q4,18606,19924.0,1318.0
3434,Madrid,Resto de criminalidad convencional,2025,Q3,24432,23255.0,1177.0
3372,Madrid,Estafas informáticas,2025,Q1,8307,9222.0,915.0
3374,Madrid,Estafas informáticas,2025,Q3,8071,7301.0,770.0
3410,Madrid,Hurtos,2025,Q3,16559,17087.0,528.0
3433,Madrid,Resto de criminalidad convencional,2025,Q2,24708,24210.0,498.0
3468,Madrid,"Robos con fuerza en domicilios, establecimient...",2025,Q1,1343,1793.0,450.0
3373,Madrid,Estafas informáticas,2025,Q2,7784,8122.0,338.0
3481,Madrid,Robos con violencia e intimidación,2025,Q2,1905,2224.0,319.0
3432,Madrid,Resto de criminalidad convencional,2025,Q1,23972,23655.0,317.0
3435,Madrid,Resto de criminalidad convencional,2025,Q4,24322,24036.0,286.0
3518,Madrid,Tráfico de drogas,2025,Q3,1033,753.0,280.0
3420,Madrid,Otros ciberdelitos,2025,Q1,1265,993.0,272.0
3519,Madrid,Tráfico de drogas,2025,Q4,1125,865.0,260.0
3480,Madrid,Robos con violencia e intimidación,2025,Q1,1748,2005.0,257.0
3423,Madrid,Otros ciberdelitos,2025,Q4,800,1054.0,254.0
6442,Valdemoro,Resto de criminalidad convencional,2025,Q3,361,590.0,229.0

In [32]:
# ==========================================
# PREPARACIÓN DEL DATASET DE MODELADO
# ==========================================

# Nos quedamos solo con filas que tienen 4 lags completos
df_ml = df_modelo.dropna(
    subset=[
        "lag_1",
        "lag_2",
        "lag_3",
        "lag_4",
        "media_movil_4",
        "tendencia_reciente",
        "variacion_interanual",
    ]
).copy()

# Variables predictoras
features = [
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "media_movil_4",
    "tendencia_reciente",
    "variacion_interanual",
    "num_trimestre",
    "municipio",
    "tipo de crimen",
]

X = df_ml[features].copy()

# Variable objetivo
y = df_ml["conteo"].copy()

print("Dimensiones X:", X.shape)
print("Dimensiones y:", y.shape)

X.head()

Dimensiones X: (4480, 10)
Dimensiones y: (4480,)

,lag_1,lag_2,lag_3,lag_4,media_movil_4,tendencia_reciente,variacion_interanual,num_trimestre,municipio,tipo de crimen
4,1.0,4.0,2.0,1.0,2.00,-3.0,0.0,1,Alcalá de Henares,Agresión sexual con penetración
5,7.0,1.0,4.0,2.0,3.50,6.0,5.0,2,Alcalá de Henares,Agresión sexual con penetración
6,2.0,7.0,1.0,4.0,3.50,-5.0,-2.0,3,Alcalá de Henares,Agresión sexual con penetración
7,3.0,2.0,7.0,1.0,3.25,1.0,2.0,4,Alcalá de Henares,Agresión sexual con penetración
8,1.0,3.0,2.0,7.0,3.25,-2.0,-6.0,1,Alcalá de Henares,Agresión sexual con penetración

In [33]:
# ==========================================
# SPLIT TEMPORAL
# ==========================================

train_mask = df_ml["año"] < 2025
test_mask = df_ml["año"] == 2025

X_train = X[train_mask].copy()
X_test = X[test_mask].copy()

y_train = y[train_mask].copy()
y_test = y[test_mask].copy()

print("Train:", X_train.shape)
print("Test:", X_test.shape)

print("\nAños train:")
print(df_ml.loc[train_mask, "año"].value_counts().sort_index())

print("\nAños test:")
print(df_ml.loc[test_mask, "año"].value_counts().sort_index())

Train: (2176, 10)
Test: (2304, 10)

Años train:
año
2024    2176
Name: count, dtype: int64

Años test:
año
2025    2304
Name: count, dtype: int64

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

# ==========================================
# PREPROCESAMIENTO
# ==========================================

variables_numericas = [
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "media_movil_4",
    "tendencia_reciente",
    "variacion_interanual",
    "num_trimestre"
]

variables_categoricas = [
    "municipio",
    "tipo de crimen"
]

preprocesador = ColumnTransformer(
    transformers=[
        ("num", "passthrough", variables_numericas),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            variables_categoricas
        )
    ]
)

# ==========================================
# RANDOM FOREST
# ==========================================

modelo_rf = Pipeline(
    steps=[
        ("preprocesador", preprocesador),
        (
            "modelo",
            RandomForestRegressor(
                n_estimators=300,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

# Entrenamiento
modelo_rf.fit(X_train, y_train)

print("Random Forest entrenado correctamente.")

Random Forest entrenado correctamente.

In [35]:
# ==========================================
# PREDICCIÓN RANDOM FOREST - 2025
# ==========================================

y_pred_rf = modelo_rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)

rmse_rf = np.sqrt(
    mean_squared_error(y_test, y_pred_rf)
)

r2_rf = r2_score(y_test, y_pred_rf)

wape_rf = (
    np.abs(y_test.values - y_pred_rf).sum()
    / np.abs(y_test.values).sum()
) * 100

print("RESULTADOS RANDOM FOREST - 2025")
print("=" * 40)
print(f"MAE:  {mae_rf:.2f}")
print(f"RMSE: {rmse_rf:.2f}")
print(f"R²:   {r2_rf:.4f}")
print(f"WAPE: {wape_rf:.2f}%")

RESULTADOS RANDOM FOREST - 2025
========================================
MAE:  17.07
RMSE: 114.45
R²:   0.9924
WAPE: 10.55%

In [36]:
from sklearn.ensemble import GradientBoostingRegressor

# ==========================================
# GRADIENT BOOSTING
# ==========================================

modelo_gb = Pipeline(
    steps=[
        ("preprocesador", preprocesador),
        (
            "modelo",
            GradientBoostingRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=3,
                random_state=42
            )
        )
    ]
)

# Entrenamiento
modelo_gb.fit(X_train, y_train)

print("Gradient Boosting entrenado correctamente.")

Gradient Boosting entrenado correctamente.

In [37]:
# ==========================================
# PREDICCIÓN GRADIENT BOOSTING - 2025
# ==========================================

y_pred_gb = modelo_gb.predict(X_test)

mae_gb = mean_absolute_error(
    y_test,
    y_pred_gb
)

rmse_gb = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_gb
    )
)

r2_gb = r2_score(
    y_test,
    y_pred_gb
)

wape_gb = (
    np.abs(y_test.values - y_pred_gb).sum()
    / np.abs(y_test.values).sum()
) * 100

print("RESULTADOS GRADIENT BOOSTING - 2025")
print("=" * 40)

print(f"MAE:  {mae_gb:.2f}")
print(f"RMSE: {rmse_gb:.2f}")
print(f"R²:   {r2_gb:.4f}")
print(f"WAPE: {wape_gb:.2f}%")

RESULTADOS GRADIENT BOOSTING - 2025
========================================
MAE:  15.12
RMSE: 86.30
R²:   0.9957
WAPE: 9.35%

In [38]:
# ==========================================
# COMPARACIÓN DE MODELOS
# ==========================================

resultados = pd.DataFrame({
    "Modelo": [
        "Baseline estacional",
        "Random Forest",
        "Gradient Boosting"
    ],
    
    "MAE": [
        mae_baseline,
        mae_rf,
        mae_gb
    ],
    
    "RMSE": [
        rmse_baseline,
        rmse_rf,
        rmse_gb
    ],
    
    "R2": [
        r2_baseline,
        r2_rf,
        r2_gb
    ],
    
    "WAPE (%)": [
        wape_baseline,
        wape_rf,
        wape_gb
    ]
})

resultados.round(3)

                Modelo     MAE     RMSE     R2  WAPE (%)
0  Baseline estacional  18.432  112.506  0.993    11.390
1        Random Forest  17.066  114.451  0.992    10.546
2    Gradient Boosting  15.124   86.305  0.996     9.346

In [39]:
# ==========================================
# VALIDACIÓN RECURSIVA - PREPARACIÓN
# ==========================================

# Histórico conocido: solo hasta finales de 2024
df_historico = df_modelo[
    df_modelo["año"] <= 2024
].copy()

# Series que queremos predecir en 2025
series_2025 = (
    df_modelo[df_modelo["año"] == 2025]
    [["municipio", "tipo de crimen"]]
    .drop_duplicates()
)

print("Series a predecir:", len(series_2025))

Series a predecir: 592

In [40]:
# ==========================================
# PREDICCIÓN RECURSIVA 2025
# ==========================================

predicciones_recursivas = []

for trimestre_num in [1, 2, 3, 4]:

    trimestre = f"Q{trimestre_num}"

    filas_prediccion = []

    for _, serie in series_2025.iterrows():

        municipio = serie["municipio"]
        tipo_crimen = serie["tipo de crimen"]

        # Histórico disponible para esta serie
        historial = df_historico[
            (df_historico["municipio"] == municipio) &
            (df_historico["tipo de crimen"] == tipo_crimen)
        ].sort_values(
            ["año", "num_trimestre"]
        )

        # Necesitamos al menos 4 valores anteriores
        if len(historial) < 4:
            continue

        ultimos_4 = historial["conteo"].tail(4).values

        lag_1 = ultimos_4[-1]
        lag_2 = ultimos_4[-2]
        lag_3 = ultimos_4[-3]
        lag_4 = ultimos_4[-4]

        media_movil_4 = np.mean(
            [lag_1, lag_2, lag_3, lag_4]
        )

        tendencia_reciente = lag_1 - lag_2

        variacion_interanual = lag_1 - lag_4

        filas_prediccion.append({
            "municipio": municipio,
            "tipo de crimen": tipo_crimen,
            "lag_1": lag_1,
            "lag_2": lag_2,
            "lag_3": lag_3,
            "lag_4": lag_4,
            "media_movil_4": media_movil_4,
            "tendencia_reciente": tendencia_reciente,
            "variacion_interanual": variacion_interanual,
            "num_trimestre": trimestre_num
        })

    X_futuro = pd.DataFrame(filas_prediccion)

    # Predicción con Gradient Boosting
    predicciones = modelo_gb.predict(X_futuro)

    # Los conteos no pueden ser negativos
    predicciones = np.maximum(
        predicciones,
        0
    )

    X_futuro["conteo_predicho"] = predicciones
    X_futuro["año"] = 2025
    X_futuro["trimestre"] = trimestre

    predicciones_recursivas.append(
        X_futuro.copy()
    )

    # Incorporamos las predicciones al histórico
    # para poder utilizarlas como lags del siguiente trimestre

    nuevas_filas = X_futuro[
        [
            "municipio",
            "tipo de crimen",
            "año",
            "trimestre",
            "num_trimestre",
            "conteo_predicho"
        ]
    ].copy()

    nuevas_filas = nuevas_filas.rename(
        columns={
            "conteo_predicho": "conteo"
        }
    )

    df_historico = pd.concat(
        [
            df_historico,
            nuevas_filas
        ],
        ignore_index=True
    )

# Unimos Q1-Q4
df_pred_recursiva = pd.concat(
    predicciones_recursivas,
    ignore_index=True
)

print(
    "Predicciones generadas:",
    len(df_pred_recursiva)
)

df_pred_recursiva[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo_predicho"
    ]
].head(10)

Predicciones generadas: 2304

,municipio,tipo de crimen,año,trimestre,conteo_predicho
0,Alcalá de Henares,Agresión sexual con penetración,2025,Q1,4.165859
1,Alcalá de Henares,Delitos contra la libertad sexual,2025,Q1,17.226655
2,Alcalá de Henares,Delitos graves y menos graves de lesiones y ri...,2025,Q1,16.078845
3,Alcalá de Henares,Estafas informáticas,2025,Q1,489.656634
4,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,2025,Q1,1.713586
5,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,2025,Q1,4.133930
6,Alcalá de Henares,Hurtos,2025,Q1,556.744562
7,Alcalá de Henares,Otros ciberdelitos,2025,Q1,70.545051
8,Alcalá de Henares,Resto de criminalidad convencional,2025,Q1,1095.647097
9,Alcalá de Henares,Resto de delitos contra la libertad sexual,2025,Q1,15.473173

In [41]:
# ==========================================
# COMPARAR PREDICCIÓN RECURSIVA CON 2025 REAL
# ==========================================

# Valores reales de 2025
df_real_2025 = df_modelo[
    df_modelo["año"] == 2025
][
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo"
    ]
].copy()

# Cruzamos predicciones y valores reales
df_validacion_recursiva = df_pred_recursiva.merge(
    df_real_2025,
    on=[
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre"
    ],
    how="inner"
)

print(
    "Observaciones comparadas:",
    len(df_validacion_recursiva)
)

df_validacion_recursiva[
    [
        "municipio",
        "tipo de crimen",
        "trimestre",
        "conteo",
        "conteo_predicho"
    ]
].head(10)

Observaciones comparadas: 2304

,municipio,tipo de crimen,trimestre,conteo,conteo_predicho
0,Alcalá de Henares,Agresión sexual con penetración,Q1,5,4.165859
1,Alcalá de Henares,Delitos contra la libertad sexual,Q1,18,17.226655
2,Alcalá de Henares,Delitos graves y menos graves de lesiones y ri...,Q1,17,16.078845
3,Alcalá de Henares,Estafas informáticas,Q1,537,489.656634
4,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,Q1,1,1.713586
5,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,Q1,3,4.133930
6,Alcalá de Henares,Hurtos,Q1,521,556.744562
7,Alcalá de Henares,Otros ciberdelitos,Q1,112,70.545051
8,Alcalá de Henares,Resto de criminalidad convencional,Q1,1088,1095.647097
9,Alcalá de Henares,Resto de delitos contra la libertad sexual,Q1,13,15.473173

In [42]:
# ==========================================
# MÉTRICAS RECURSIVAS POR TRIMESTRE
# ==========================================

resultados_recursivos = []

for trimestre in ["Q1", "Q2", "Q3", "Q4"]:

    datos = df_validacion_recursiva[
        df_validacion_recursiva["trimestre"] == trimestre
    ]

    y_real_trim = datos["conteo"]
    y_pred_trim = datos["conteo_predicho"]

    mae = mean_absolute_error(
        y_real_trim,
        y_pred_trim
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_real_trim,
            y_pred_trim
        )
    )

    r2 = r2_score(
        y_real_trim,
        y_pred_trim
    )

    wape = (
        np.abs(
            y_real_trim.values -
            y_pred_trim.values
        ).sum()
        /
        np.abs(
            y_real_trim.values
        ).sum()
    ) * 100

    resultados_recursivos.append({
        "Trimestre": trimestre,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "WAPE (%)": wape
    })

resultados_recursivos = pd.DataFrame(
    resultados_recursivos
)

resultados_recursivos.round(3)

  Trimestre     MAE     RMSE     R2  WAPE (%)
0        Q1  13.850   60.653  0.998     8.506
1        Q2  13.266   49.373  0.999     8.090
2        Q3  18.308  119.863  0.991    11.300
3        Q4  18.300   95.952  0.995    11.548

In [43]:
# ==========================================
# VALIDACIÓN RECURSIVA SIN MADRID CAPITAL
# ==========================================

df_rec_sin_madrid = df_validacion_recursiva[
    df_validacion_recursiva["municipio"] != "Madrid"
].copy()

y_real_sm = df_rec_sin_madrid["conteo"]
y_pred_sm = df_rec_sin_madrid["conteo_predicho"]

mae_rec_sm = mean_absolute_error(y_real_sm, y_pred_sm)

rmse_rec_sm = np.sqrt(
    mean_squared_error(y_real_sm, y_pred_sm)
)

r2_rec_sm = r2_score(y_real_sm, y_pred_sm)

wape_rec_sm = (
    np.abs(y_real_sm.values - y_pred_sm.values).sum()
    / np.abs(y_real_sm.values).sum()
) * 100

print("VALIDACIÓN RECURSIVA 2025 - SIN MADRID")
print("=" * 45)
print(f"MAE:  {mae_rec_sm:.2f}")
print(f"RMSE: {rmse_rec_sm:.2f}")
print(f"R²:   {r2_rec_sm:.4f}")
print(f"WAPE: {wape_rec_sm:.2f}%")

VALIDACIÓN RECURSIVA 2025 - SIN MADRID
=============================================
MAE:  10.12
RMSE: 25.35
R²:   0.9694
WAPE: 16.55%

In [44]:
# ==========================================
# RENDIMIENTO POR TIPO DE CRIMEN
# ==========================================

resultados_tipo = []

for tipo, datos in df_validacion_recursiva.groupby("tipo de crimen"):

    y_real_tipo = datos["conteo"]
    y_pred_tipo = datos["conteo_predicho"]

    mae = mean_absolute_error(
        y_real_tipo,
        y_pred_tipo
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_real_tipo,
            y_pred_tipo
        )
    )

    wape = (
        np.abs(
            y_real_tipo.values -
            y_pred_tipo.values
        ).sum()
        /
        np.abs(
            y_real_tipo.values
        ).sum()
    ) * 100

    resultados_tipo.append({
        "Tipo de crimen": tipo,
        "MAE": mae,
        "RMSE": rmse,
        "WAPE (%)": wape,
        "Volumen real": y_real_tipo.sum()
    })

resultados_tipo = pd.DataFrame(
    resultados_tipo
).sort_values(
    "WAPE (%)"
)

resultados_tipo.round(2)

,Tipo de crimen,MAE,RMSE,WAPE (%),Volumen real
8,Resto de criminalidad convencional,63.79,138.59,5.99,153291
6,Hurtos,63.10,244.53,8.48,107165
14,Sustracciones de vehículos,5.38,9.35,11.81,6557
12,Robos con violencia e intimidación,8.37,31.66,12.38,9730
3,Estafas informáticas,53.08,183.74,13.69,55844
15,Tráfico de drogas,5.13,18.81,16.58,4458
11,"Robos con fuerza en domicilios, establecimient...",13.63,40.08,17.62,11134
10,Robos con fuerza en domicilios,9.66,27.26,19.44,7158
1,Delitos contra la libertad sexual,4.05,9.59,20.25,2879
2,Delitos graves y menos graves de lesiones y ri...,4.77,17.12,20.28,3389
9,Resto de delitos contra la libertad sexual,3.71,10.72,23.77,2248
7,Otros ciberdelitos,15.28,41.07,26.89,8181
0,Agresión sexual con penetración,1.84,3.40,41.94,631
5,Homicidios dolosos y asesinatos en grado tenta...,1.09,1.38,118.42,133
4,Homicidios dolosos y asesinatos consumados,1.00,1.30,515.23,28
13,Secuestro,1.01,1.15,1209.99,12

In [45]:
# ==========================================
# ANÁLISIS ESPECÍFICO - TRÁFICO DE DROGAS
# ==========================================

df_drogas = df_validacion_recursiva[
    df_validacion_recursiva["tipo de crimen"]
    .str.contains(
        "droga",
        case=False,
        na=False
    )
].copy()

resultado_drogas = (
    df_drogas
    .groupby("trimestre")
    .agg(
        Real=("conteo", "sum"),
        Predicho=("conteo_predicho", "sum")
    )
    .reset_index()
)

resultado_drogas["Error"] = (
    resultado_drogas["Predicho"]
    - resultado_drogas["Real"]
)

resultado_drogas["Error (%)"] = (
    np.abs(resultado_drogas["Error"])
    / resultado_drogas["Real"]
) * 100

resultado_drogas.round(2)

  trimestre  Real  Predicho   Error  Error (%)
0        Q1   918   1047.89  129.89      14.15
1        Q2  1027   1155.39  128.39      12.50
2        Q3  1209   1181.75  -27.25       2.25
3        Q4  1304   1201.36 -102.64       7.87

In [46]:
# ==========================================
# PREDICCIÓN RECURSIVA Q1-Q3 2026
# ==========================================

# Partimos de todo el histórico REAL disponible hasta Q4 2025
df_historico_2026 = df_modelo[
    df_modelo["año"] <= 2025
].copy()

# Series existentes en 2025 que vamos a proyectar a 2026
series_2026 = (
    df_modelo[df_modelo["año"] == 2025]
    [["municipio", "tipo de crimen"]]
    .drop_duplicates()
)

predicciones_2026 = []

# Predecimos Q1, Q2 y Q3
for trimestre_num in [1, 2, 3]:

    trimestre = f"Q{trimestre_num}"

    filas_prediccion = []

    for _, serie in series_2026.iterrows():

        municipio = serie["municipio"]
        tipo_crimen = serie["tipo de crimen"]

        # Histórico disponible para cada serie
        historial = df_historico_2026[
            (df_historico_2026["municipio"] == municipio) &
            (df_historico_2026["tipo de crimen"] == tipo_crimen)
        ].sort_values(
            ["año", "num_trimestre"]
        )

        # Necesitamos al menos 4 observaciones anteriores
        if len(historial) < 4:
            continue

        ultimos_4 = historial["conteo"].tail(4).values

        lag_1 = ultimos_4[-1]
        lag_2 = ultimos_4[-2]
        lag_3 = ultimos_4[-3]
        lag_4 = ultimos_4[-4]

        media_movil_4 = np.mean(
            [lag_1, lag_2, lag_3, lag_4]
        )

        tendencia_reciente = lag_1 - lag_2

        variacion_interanual = lag_1 - lag_4

        filas_prediccion.append({
            "municipio": municipio,
            "tipo de crimen": tipo_crimen,
            "lag_1": lag_1,
            "lag_2": lag_2,
            "lag_3": lag_3,
            "lag_4": lag_4,
            "media_movil_4": media_movil_4,
            "tendencia_reciente": tendencia_reciente,
            "variacion_interanual": variacion_interanual,
            "num_trimestre": trimestre_num
        })

    # Dataset para realizar la predicción
    X_futuro = pd.DataFrame(filas_prediccion)

    # Predicción con Gradient Boosting
    predicciones = modelo_gb.predict(X_futuro)

    # Evitamos predicciones negativas
    predicciones = np.maximum(
        predicciones,
        0
    )

    X_futuro["conteo_predicho"] = predicciones
    X_futuro["año"] = 2026
    X_futuro["trimestre"] = trimestre

    # Guardamos resultados
    predicciones_2026.append(
        X_futuro.copy()
    )

    # Incorporamos las predicciones al histórico
    # para alimentar el siguiente trimestre
    nuevas_filas = X_futuro[
        [
            "municipio",
            "tipo de crimen",
            "año",
            "trimestre",
            "num_trimestre",
            "conteo_predicho"
        ]
    ].copy()

    nuevas_filas = nuevas_filas.rename(
        columns={
            "conteo_predicho": "conteo"
        }
    )

    df_historico_2026 = pd.concat(
        [
            df_historico_2026,
            nuevas_filas
        ],
        ignore_index=True
    )


# ==========================================
# UNIR RESULTADOS Q1-Q3 2026
# ==========================================

df_pred_2026 = pd.concat(
    predicciones_2026,
    ignore_index=True
)

print(
    "Predicciones 2026 generadas:",
    len(df_pred_2026)
)

print(
    "\nPredicciones por trimestre:"
)

print(
    df_pred_2026["trimestre"].value_counts().sort_index()
)

df_pred_2026[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "conteo_predicho"
    ]
].head(20)

Predicciones 2026 generadas: 1776

Predicciones por trimestre:
trimestre
Q1    592
Q2    592
Q3    592
Name: count, dtype: int64

,municipio,tipo de crimen,año,trimestre,conteo_predicho
0,Alcalá de Henares,Agresión sexual con penetración,2026,Q1,4.137117
1,Alcalá de Henares,Delitos contra la libertad sexual,2026,Q1,20.316384
2,Alcalá de Henares,Delitos graves y menos graves de lesiones y ri...,2026,Q1,17.769420
3,Alcalá de Henares,Estafas informáticas,2026,Q1,436.119962
4,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,2026,Q1,1.692693
5,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,2026,Q1,3.193027
6,Alcalá de Henares,Hurtos,2026,Q1,556.417015
7,Alcalá de Henares,Otros ciberdelitos,2026,Q1,81.977520
8,Alcalá de Henares,Resto de criminalidad convencional,2026,Q1,1097.185895
9,Alcalá de Henares,Resto de delitos contra la libertad sexual,2026,Q1,17.769420
10,Alcalá de Henares,Robos con fuerza en domicilios,2026,Q1,45.047556
11,Alcalá de Henares,"Robos con fuerza en domicilios, establecimient...",2026,Q1,75.448563
12,Alcalá de Henares,Robos con violencia e intimidación,2026,Q1,31.148139
13,Alcalá de Henares,Secuestro,2026,Q1,1.692693
14,Alcalá de Henares,Sustracciones de vehículos,2026,Q1,72.891811
15,Alcalá de Henares,Tráfico de drogas,2026,Q1,14.225123
16,Alcobendas,Agresión sexual con penetración,2026,Q1,2.768298
17,Alcobendas,Delitos contra la libertad sexual,2026,Q1,13.246599
18,Alcobendas,Delitos graves y menos graves de lesiones y ri...,2026,Q1,10.093058
19,Alcobendas,Estafas informáticas,2026,Q1,228.925757

In [47]:
# ==========================================
# COMPARACIÓN 2025 REAL VS 2026 PREDICHO
# ==========================================

# Datos reales Q1-Q3 2025
real_2025_q1_q3 = (
    df_modelo[
        (df_modelo["año"] == 2025) &
        (df_modelo["num_trimestre"].isin([1, 2, 3]))
    ]
    .groupby("trimestre")["conteo"]
    .sum()
)

# Predicciones Q1-Q3 2026
pred_2026_q1_q3 = (
    df_pred_2026
    .groupby("trimestre")["conteo_predicho"]
    .sum()
)

comparacion_global = pd.DataFrame({
    "Real 2025": real_2025_q1_q3,
    "Predicho 2026": pred_2026_q1_q3
})

comparacion_global["Variación absoluta"] = (
    comparacion_global["Predicho 2026"]
    - comparacion_global["Real 2025"]
)

comparacion_global["Variación (%)"] = (
    comparacion_global["Variación absoluta"]
    / comparacion_global["Real 2025"]
) * 100

comparacion_global.round(2)

           Real 2025  Predicho 2026  Variación absoluta  Variación (%)
trimestre
Q1             94584       94303.70             -280.30          -0.30
Q2             94905       94228.99             -676.01          -0.71
Q3             93699       93975.74              276.74           0.30

In [48]:
# ==========================================
# COMPARACIÓN POR TIPO DE CRIMEN
# Q1-Q3 2025 REAL VS Q1-Q3 2026 PREDICHO
# ==========================================

real_tipo_2025 = (
    df_modelo[
        (df_modelo["año"] == 2025) &
        (df_modelo["num_trimestre"].isin([1, 2, 3]))
    ]
    .groupby("tipo de crimen")["conteo"]
    .sum()
)

pred_tipo_2026 = (
    df_pred_2026
    .groupby("tipo de crimen")["conteo_predicho"]
    .sum()
)

comparacion_tipo = pd.DataFrame({
    "Real Q1-Q3 2025": real_tipo_2025,
    "Predicho Q1-Q3 2026": pred_tipo_2026
})

comparacion_tipo["Variación"] = (
    comparacion_tipo["Predicho Q1-Q3 2026"]
    - comparacion_tipo["Real Q1-Q3 2025"]
)

comparacion_tipo["Variación (%)"] = (
    comparacion_tipo["Variación"]
    / comparacion_tipo["Real Q1-Q3 2025"]
) * 100

comparacion_tipo = comparacion_tipo.sort_values(
    "Variación (%)",
    ascending=False
)

comparacion_tipo.round(2)

,Real Q1-Q3 2025,Predicho Q1-Q3 2026,Variación,Variación (%)
tipo de crimen,,,,
Secuestro,8,113.97,105.97,1324.63
Homicidios dolosos y asesinatos consumados,16,126.18,110.18,688.63
Homicidios dolosos y asesinatos en grado tentativa,97,190.93,93.93,96.84
Tráfico de drogas,3167,3870.45,703.45,22.21
Hurtos,80224,83415.61,3191.61,3.98
Robos con fuerza en domicilios,5341,5514.10,173.10,3.24
Delitos graves y menos graves de lesiones y riña tumultuaria,2597,2656.44,59.44,2.29
Agresión sexual con penetración,505,512.45,7.45,1.48
Sustracciones de vehículos,4886,4918.49,32.49,0.66
Resto de criminalidad convencional,115332,115221.41,-110.59,-0.10
"Robos con fuerza en domicilios, establecimientos y otras instalaciones",8345,7978.36,-366.64,-4.39
Estafas informáticas,44528,41996.36,-2531.64,-5.69
Resto de delitos contra la libertad sexual,1724,1619.50,-104.50,-6.06
Delitos contra la libertad sexual,2229,2073.72,-155.28,-6.97
Robos con violencia e intimidación,7535,6620.20,-914.80,-12.14
Otros ciberdelitos,6654,5680.26,-973.74,-14.63

In [49]:
# ==========================================
# BENCHMARK EVENTOS DE BAJA FRECUENCIA
# VALIDACIÓN SOBRE 2025
# ==========================================

categorias_raras = [
    "Secuestro",
    "Homicidios dolosos y asesinatos consumados",
    "Homicidios dolosos y asesinatos en grado tentativa"
]

# Seleccionamos únicamente las tres categorías
df_raras = df_modelo[
    df_modelo["tipo de crimen"].isin(categorias_raras)
].copy()

# Solo 2025, porque queremos validar contra datos reales
test_raras = df_raras[
    df_raras["año"] == 2025
].copy()

# Método 1: mismo trimestre del año anterior
test_raras["pred_lag4"] = test_raras["lag_4"]

# Método 2: media últimos cuatro trimestres
test_raras["pred_media4"] = (
    test_raras[
        ["lag_1", "lag_2", "lag_3", "lag_4"]
    ].mean(axis=1)
)

# Método 3: mediana últimos cuatro trimestres
test_raras["pred_mediana4"] = (
    test_raras[
        ["lag_1", "lag_2", "lag_3", "lag_4"]
    ].median(axis=1)
)

print(
    "Observaciones:",
    len(test_raras)
)

test_raras[
    [
        "municipio",
        "tipo de crimen",
        "trimestre",
        "conteo",
        "pred_lag4",
        "pred_media4",
        "pred_mediana4"
    ]
].head(20)

Observaciones: 444

,municipio,tipo de crimen,trimestre,conteo,pred_lag4,pred_media4,pred_mediana4
56,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,Q1,1,0.0,0.25,0.0
57,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,Q2,0,0.0,0.50,0.5
58,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,Q3,0,0.0,0.50,0.5
59,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,Q4,0,1.0,0.50,0.5
68,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,Q1,3,7.0,3.25,3.0
69,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,Q2,2,0.0,2.25,2.0
70,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,Q3,1,5.0,2.75,2.5
71,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,Q4,2,1.0,1.75,1.5
164,Alcalá de Henares,Secuestro,Q1,1,0.0,0.00,0.0
165,Alcalá de Henares,Secuestro,Q2,0,0.0,0.25,0.0
166,Alcalá de Henares,Secuestro,Q3,0,0.0,0.25,0.0
167,Alcalá de Henares,Secuestro,Q4,0,0.0,0.25,0.0
248,Alcobendas,Homicidios dolosos y asesinatos consumados,Q1,0,0.0,0.25,0.0
249,Alcobendas,Homicidios dolosos y asesinatos consumados,Q2,0,1.0,0.25,0.0
250,Alcobendas,Homicidios dolosos y asesinatos consumados,Q3,0,0.0,0.00,0.0
251,Alcobendas,Homicidios dolosos y asesinatos consumados,Q4,0,0.0,0.00,0.0
260,Alcobendas,Homicidios dolosos y asesinatos en grado tenta...,Q1,1,0.0,0.25,0.0
261,Alcobendas,Homicidios dolosos y asesinatos en grado tenta...,Q2,0,0.0,0.50,0.5
262,Alcobendas,Homicidios dolosos y asesinatos en grado tenta...,Q3,1,0.0,0.50,0.5
263,Alcobendas,Homicidios dolosos y asesinatos en grado tenta...,Q4,2,1.0,0.75,1.0

In [52]:
# ==========================================
# COMPARACIÓN GLOBAL DE LOS 3 MÉTODOS
# CORREGIDA: EXCLUYE FILAS SIN HISTÓRICO SUFICIENTE
# ==========================================

metodos = {
    "Lag 4 estacional": "pred_lag4",
    "Media móvil 4": "pred_media4",
    "Mediana móvil 4": "pred_mediana4"
}

# Nos quedamos solo con filas donde los 3 métodos
# tienen una predicción válida
test_raras_validas = test_raras.dropna(
    subset=[
        "pred_lag4",
        "pred_media4",
        "pred_mediana4"
    ]
).copy()

print("Observaciones originales:", len(test_raras))
print("Observaciones válidas para comparar:", len(test_raras_validas))

resultados_raras = []

for nombre, columna in metodos.items():

    y_real_raras = test_raras_validas["conteo"]
    y_pred_raras = test_raras_validas[columna]

    mae = mean_absolute_error(
        y_real_raras,
        y_pred_raras
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_real_raras,
            y_pred_raras
        )
    )

    wape = (
        np.abs(
            y_real_raras.values -
            y_pred_raras.values
        ).sum()
        /
        np.abs(y_real_raras.values).sum()
    ) * 100

    resultados_raras.append({
        "Método": nombre,
        "MAE": mae,
        "RMSE": rmse,
        "WAPE (%)": wape
    })

resultados_raras = pd.DataFrame(
    resultados_raras
).sort_values(
    "WAPE (%)"
)

resultados_raras.round(3)

Observaciones originales: 444
Observaciones válidas para comparar: 432

             Método    MAE   RMSE  WAPE (%)
2   Mediana móvil 4  0.231  0.861    57.803
1     Media móvil 4  0.259  0.759    64.595
0  Lag 4 estacional  0.280  0.835    69.942

In [53]:
# ==========================================
# COMPARACIÓN POR CATEGORÍA
# ==========================================

resultados_raras_tipo = []

for tipo, datos in test_raras_validas.groupby(
    "tipo de crimen"
):

    for nombre, columna in metodos.items():

        y_real_tipo = datos["conteo"]
        y_pred_tipo = datos[columna]

        mae = mean_absolute_error(
            y_real_tipo,
            y_pred_tipo
        )

        rmse = np.sqrt(
            mean_squared_error(
                y_real_tipo,
                y_pred_tipo
            )
        )

        wape = (
            np.abs(
                y_real_tipo.values -
                y_pred_tipo.values
            ).sum()
            /
            np.abs(y_real_tipo.values).sum()
        ) * 100

        resultados_raras_tipo.append({
            "Tipo de crimen": tipo,
            "Método": nombre,
            "MAE": mae,
            "RMSE": rmse,
            "WAPE (%)": wape,
            "Casos reales": y_real_tipo.sum()
        })

resultados_raras_tipo = pd.DataFrame(
    resultados_raras_tipo
).sort_values(
    ["Tipo de crimen", "WAPE (%)"]
)

resultados_raras_tipo.round(3)

,Tipo de crimen,Método,MAE,RMSE,WAPE (%),Casos reales
0,Homicidios dolosos y asesinatos consumados,Lag 4 estacional,0.201,0.795,103.571,28
2,Homicidios dolosos y asesinatos consumados,Mediana móvil 4,0.205,0.818,105.357,28
1,Homicidios dolosos y asesinatos consumados,Media móvil 4,0.231,0.782,118.750,28
5,Homicidios dolosos y asesinatos en grado tenta...,Mediana móvil 4,0.444,1.223,48.120,133
4,Homicidios dolosos y asesinatos en grado tenta...,Media móvil 4,0.476,1.025,51.504,133
3,Homicidios dolosos y asesinatos en grado tenta...,Lag 4 estacional,0.562,1.158,60.902,133
8,Secuestro,Mediana móvil 4,0.045,0.239,54.167,12
7,Secuestro,Media móvil 4,0.069,0.252,83.333,12
6,Secuestro,Lag 4 estacional,0.076,0.344,91.667,12

In [54]:
# ==========================================
# PREDICCIÓN RECURSIVA 2026
# CATEGORÍAS DE MUY BAJA FRECUENCIA
# MEDIANA MÓVIL DE 4 TRIMESTRES
# ==========================================

categorias_raras = [
    "Secuestro",
    "Homicidios dolosos y asesinatos consumados",
    "Homicidios dolosos y asesinatos en grado tentativa"
]

# Histórico real hasta Q4 2025
df_hist_raras = df_modelo[
    (df_modelo["año"] <= 2025) &
    (df_modelo["tipo de crimen"].isin(categorias_raras))
].copy()

series_raras_2026 = (
    df_hist_raras[
        df_hist_raras["año"] == 2025
    ][["municipio", "tipo de crimen"]]
    .drop_duplicates()
)

predicciones_raras_2026 = []

for trimestre_num in [1, 2, 3]:

    trimestre = f"Q{trimestre_num}"

    nuevas_predicciones = []

    for _, serie in series_raras_2026.iterrows():

        municipio = serie["municipio"]
        tipo_crimen = serie["tipo de crimen"]

        historial = df_hist_raras[
            (df_hist_raras["municipio"] == municipio) &
            (df_hist_raras["tipo de crimen"] == tipo_crimen)
        ].sort_values(
            ["año", "num_trimestre"]
        )

        if len(historial) < 4:
            continue

        ultimos_4 = historial["conteo"].tail(4)

        prediccion = ultimos_4.median()

        nuevas_predicciones.append({
            "municipio": municipio,
            "tipo de crimen": tipo_crimen,
            "año": 2026,
            "trimestre": trimestre,
            "num_trimestre": trimestre_num,
            "conteo_predicho": prediccion,
            "modelo": "Mediana móvil 4",
            "nivel_confianza": "Alta incertidumbre"
        })

    nuevas_predicciones = pd.DataFrame(
        nuevas_predicciones
    )

    predicciones_raras_2026.append(
        nuevas_predicciones.copy()
    )

    # Incorporamos las predicciones al histórico
    nuevas_filas_hist = nuevas_predicciones[
        [
            "municipio",
            "tipo de crimen",
            "año",
            "trimestre",
            "num_trimestre",
            "conteo_predicho"
        ]
    ].rename(
        columns={
            "conteo_predicho": "conteo"
        }
    )

    df_hist_raras = pd.concat(
        [
            df_hist_raras,
            nuevas_filas_hist
        ],
        ignore_index=True
    )


df_pred_raras_2026 = pd.concat(
    predicciones_raras_2026,
    ignore_index=True
)

print(
    "Predicciones raras generadas:",
    len(df_pred_raras_2026)
)

df_pred_raras_2026.head(10)

Predicciones raras generadas: 333

,municipio,tipo de crimen,año,trimestre,num_trimestre,conteo_predicho,modelo,nivel_confianza
0,Alcalá de Henares,Homicidios dolosos y asesinatos consumados,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
1,Alcalá de Henares,Homicidios dolosos y asesinatos en grado tenta...,2026,Q1,1,2.0,Mediana móvil 4,Alta incertidumbre
2,Alcalá de Henares,Secuestro,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
3,Alcobendas,Homicidios dolosos y asesinatos consumados,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
4,Alcobendas,Homicidios dolosos y asesinatos en grado tenta...,2026,Q1,1,1.0,Mediana móvil 4,Alta incertidumbre
5,Alcobendas,Secuestro,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
6,Alcorcón,Homicidios dolosos y asesinatos consumados,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
7,Alcorcón,Homicidios dolosos y asesinatos en grado tenta...,2026,Q1,1,0.5,Mediana móvil 4,Alta incertidumbre
8,Alcorcón,Secuestro,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre
9,Algete,Homicidios dolosos y asesinatos consumados,2026,Q1,1,0.0,Mediana móvil 4,Alta incertidumbre

In [55]:
# ==========================================
# DATASET PREDICTIVO HÍBRIDO DEFINITIVO
# ==========================================

# Copia de las predicciones generales
df_pred_final_2026 = df_pred_2026.copy()

# Etiquetamos el modelo general
df_pred_final_2026["modelo"] = "Gradient Boosting"
df_pred_final_2026["nivel_confianza"] = "Estándar"

# Eliminamos las categorías raras
# que fueron predichas inicialmente por Gradient Boosting
df_pred_final_2026 = df_pred_final_2026[
    ~df_pred_final_2026[
        "tipo de crimen"
    ].isin(categorias_raras)
].copy()

# Unimos las predicciones específicas
df_pred_final_2026 = pd.concat(
    [
        df_pred_final_2026,
        df_pred_raras_2026
    ],
    ignore_index=True
)

# Ordenamos
df_pred_final_2026 = df_pred_final_2026.sort_values(
    [
        "municipio",
        "tipo de crimen",
        "num_trimestre"
    ]
).reset_index(drop=True)

print(
    "Total predicciones finales:",
    len(df_pred_final_2026)
)

print(
    "\nPredicciones por modelo:"
)

print(
    df_pred_final_2026["modelo"].value_counts()
)

print(
    "\nPredicciones por trimestre:"
)

print(
    df_pred_final_2026[
        "trimestre"
    ].value_counts().sort_index()
)

Total predicciones finales: 1776

Predicciones por modelo:
modelo
Gradient Boosting    1443
Mediana móvil 4       333
Name: count, dtype: int64

Predicciones por trimestre:
trimestre
Q1    592
Q2    592
Q3    592
Name: count, dtype: int64

In [56]:
# ==========================================
# COMPARACIÓN FINAL POR TIPO DE CRIMEN
# MODELO HÍBRIDO
# ==========================================

pred_tipo_2026_final = (
    df_pred_final_2026
    .groupby("tipo de crimen")["conteo_predicho"]
    .sum()
)

comparacion_tipo_final = pd.DataFrame({
    "Real Q1-Q3 2025": real_tipo_2025,
    "Predicho Q1-Q3 2026": pred_tipo_2026_final
})

comparacion_tipo_final["Variación"] = (
    comparacion_tipo_final["Predicho Q1-Q3 2026"]
    - comparacion_tipo_final["Real Q1-Q3 2025"]
)

comparacion_tipo_final["Variación (%)"] = (
    comparacion_tipo_final["Variación"]
    / comparacion_tipo_final["Real Q1-Q3 2025"]
) * 100

comparacion_tipo_final = comparacion_tipo_final.sort_values(
    "Variación (%)",
    ascending=False
)

comparacion_tipo_final.round(2)

,Real Q1-Q3 2025,Predicho Q1-Q3 2026,Variación,Variación (%)
tipo de crimen,,,,
Tráfico de drogas,3167,3870.45,703.45,22.21
Secuestro,8,9.00,1.00,12.50
Hurtos,80224,83415.61,3191.61,3.98
Robos con fuerza en domicilios,5341,5514.10,173.10,3.24
Delitos graves y menos graves de lesiones y riña tumultuaria,2597,2656.44,59.44,2.29
Agresión sexual con penetración,505,512.45,7.45,1.48
Homicidios dolosos y asesinatos consumados,16,16.12,0.12,0.78
Sustracciones de vehículos,4886,4918.49,32.49,0.66
Resto de criminalidad convencional,115332,115221.41,-110.59,-0.10
Homicidios dolosos y asesinatos en grado tentativa,97,96.38,-0.62,-0.64
"Robos con fuerza en domicilios, establecimientos y otras instalaciones",8345,7978.36,-366.64,-4.39
Estafas informáticas,44528,41996.36,-2531.64,-5.69
Resto de delitos contra la libertad sexual,1724,1619.50,-104.50,-6.06
Delitos contra la libertad sexual,2229,2073.72,-155.28,-6.97
Robos con violencia e intimidación,7535,6620.20,-914.80,-12.14
Otros ciberdelitos,6654,5680.26,-973.74,-14.63

In [57]:
# Exportar predicciones finales 2026

df_pred_final_2026.to_excel(
    "Predicciones_Criminalidad_2026.xlsx",
    index=False
)

print("Archivo exportado correctamente")
print("Número de filas:", len(df_pred_final_2026))
print("\nColumnas:")
print(df_pred_final_2026.columns.tolist())

Archivo exportado correctamente
Número de filas: 1776

Columnas:
['municipio', 'tipo de crimen', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'media_movil_4', 'tendencia_reciente', 'variacion_interanual', 'num_trimestre', 'conteo_predicho', 'año', 'trimestre', 'modelo', 'nivel_confianza']

In [58]:
print("Predicciones por trimestre:")
print(df_pred_final_2026["trimestre"].value_counts().sort_index())

duplicados = df_pred_final_2026.duplicated(
    subset=["municipio", "tipo de crimen", "año", "trimestre"]
).sum()

print("\nDuplicados:", duplicados)

print("\nValores nulos:")
print(df_pred_final_2026.isnull().sum())

Predicciones por trimestre:
trimestre
Q1    592
Q2    592
Q3    592
Name: count, dtype: int64

Duplicados: 0

Valores nulos:
municipio                 0
tipo de crimen            0
lag_1                   333
lag_2                   333
lag_3                   333
lag_4                   333
media_movil_4           333
tendencia_reciente      333
variacion_interanual    333
num_trimestre             0
conteo_predicho           0
año                       0
trimestre                 0
modelo                    0
nivel_confianza           0
dtype: int64

In [59]:
# ==========================================
# DATASET LIMPIO DE PREDICCIONES 2026
# ==========================================

df_pred_2026_limpio = df_pred_final_2026[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "num_trimestre",
        "conteo_predicho",
        "modelo",
        "nivel_confianza"
    ]
].copy()

print(df_pred_2026_limpio.shape)
print()
print(df_pred_2026_limpio.isnull().sum())

df_pred_2026_limpio.head()

(1776, 8)

municipio          0
tipo de crimen     0
año                0
trimestre          0
num_trimestre      0
conteo_predicho    0
modelo             0
nivel_confianza    0
dtype: int64

,municipio,tipo de crimen,año,trimestre,num_trimestre,conteo_predicho,modelo,nivel_confianza
0,Alcalá de Henares,Agresión sexual con penetración,2026,Q1,1,4.137117,Gradient Boosting,Estándar
1,Alcalá de Henares,Agresión sexual con penetración,2026,Q2,2,4.574096,Gradient Boosting,Estándar
2,Alcalá de Henares,Agresión sexual con penetración,2026,Q3,3,5.011932,Gradient Boosting,Estándar
3,Alcalá de Henares,Delitos contra la libertad sexual,2026,Q1,1,20.316384,Gradient Boosting,Estándar
4,Alcalá de Henares,Delitos contra la libertad sexual,2026,Q2,2,22.427383,Gradient Boosting,Estándar

In [60]:
df_pred_2026_limpio.to_csv(
    "../data/predicciones_criminalidad_2026.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV de predicciones creado correctamente.")

CSV de predicciones creado correctamente.

In [61]:
# ==========================================
# HISTÓRICO REAL 2023-2025
# ==========================================

df_historico_real = df_modelo[
    [
        "municipio",
        "tipo de crimen",
        "año",
        "trimestre",
        "num_trimestre",
        "conteo"
    ]
].copy()

df_historico_real = df_historico_real.rename(
    columns={
        "conteo": "valor"
    }
)

df_historico_real["tipo_dato"] = "Real"
df_historico_real["modelo"] = "Dato observado"
df_historico_real["nivel_confianza"] = "Real"

In [62]:
# ==========================================
# PREDICCIONES 2026
# ==========================================

df_futuro = df_pred_2026_limpio.copy()

df_futuro = df_futuro.rename(
    columns={
        "conteo_predicho": "valor"
    }
)

df_futuro["tipo_dato"] = "Predicción"

In [63]:
# ==========================================
# DATASET HISTÓRICO + FORECAST
# ==========================================

columnas_finales = [
    "municipio",
    "tipo de crimen",
    "año",
    "trimestre",
    "num_trimestre",
    "valor",
    "tipo_dato",
    "modelo",
    "nivel_confianza"
]

df_crime_lab = pd.concat(
    [
        df_historico_real[columnas_finales],
        df_futuro[columnas_finales]
    ],
    ignore_index=True
)

print("Total registros:", len(df_crime_lab))

print("\nTipo de dato:")
print(df_crime_lab["tipo_dato"].value_counts())

print("\nAños:")
print(df_crime_lab["año"].value_counts().sort_index())

print("\nNulos:")
print(df_crime_lab.isnull().sum())

Total registros: 8624

Tipo de dato:
tipo_dato
Real          6848
Predicción    1776
Name: count, dtype: int64

Años:
año
2023    2176
2024    2304
2025    2368
2026    1776
Name: count, dtype: int64

Nulos:
municipio          0
tipo de crimen     0
año                0
trimestre          0
num_trimestre      0
valor              0
tipo_dato          0
modelo             0
nivel_confianza    0
dtype: int64

In [64]:
df_crime_lab.to_csv(
    "../data/crime_lab_historico_predicciones.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset completo de Crime Lab exportado.")

Dataset completo de Crime Lab exportado.

In [65]:
print("df:", df.shape)
print(df["año"].value_counts().sort_index())

print("\ndf_modelo:", df_modelo.shape)
print(df_modelo["año"].value_counts().sort_index())

df: (6848, 16)
año
2023    2176
2024    2304
2025    2368
Name: count, dtype: int64

df_modelo: (6848, 23)
año
2023    2176
2024    2304
2025    2368
Name: count, dtype: int64

In [66]:
print("Dimensiones:", df_crime_lab.shape)

print("\nRegistros por año:")
print(df_crime_lab["año"].value_counts().sort_index())

print("\nRegistros por tipo:")
print(df_crime_lab["tipo_dato"].value_counts())

print("\nNulos:")
print(df_crime_lab.isnull().sum())

print("\nDuplicados:")
print(
    df_crime_lab.duplicated(
        subset=[
            "municipio",
            "tipo de crimen",
            "año",
            "trimestre"
        ]
    ).sum()
)

Dimensiones: (8624, 9)

Registros por año:
año
2023    2176
2024    2304
2025    2368
2026    1776
Name: count, dtype: int64

Registros por tipo:
tipo_dato
Real          6848
Predicción    1776
Name: count, dtype: int64

Nulos:
municipio          0
tipo de crimen     0
año                0
trimestre          0
num_trimestre      0
valor              0
tipo_dato          0
modelo             0
nivel_confianza    0
dtype: int64

Duplicados:
0